default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_DB_NAME'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: 3306

development:
  <<: *default

test: &test
  <<: *default
  username: <%= ENV['DATABASE_USERNAME_TEST'] %>
  password: <%= ENV['DATABASE_PASSWORD_TEST'] %>
  database: <%= ENV['DATABASE_DB_NAME_TEST'] %>
  host: <%= ENV['DATABASE_HOSTNAME_TEST'] %>

production:
  <<: *default

cucumber:
  <<: *test
